### ISSUE TITLE
Phonegap Build Failing

### ISSUE THREAD

**Issue by NTcoder** [apptentive/apptentive-cordova#40]
`
* What went wrong:
A problem occurred configuring root project 'project'.
> Could not resolve all dependencies for configuration ':_armv7DebugApkCopy'.
   > Could not find com.android.support:support-v4:26.1.0.
     Required by:
         :project:unspecified > com.apptentive:apptentive-android:4.1.2
   > Could not find com.android.support:appcompat-v7:26.1.0.
     Required by:
         :project:unspecified > com.apptentive:apptentive-android:4.1.2
   > Could not find com.android.support:cardview-v7:26.1.0.
     Required by:
         :project:unspecified > com.apptentive:apptentive-android:4.1.2
   > Could not find com.android.support:design:26.1.0.
     Required by:
         :project:unspecified > com.apptentive:apptentive-android:4.1.2
   > Could not find com.android.support:support-v4:26.1.0.
     Required by:
         :project:unspecified > org.xwalk:xwalk_core_library:23.53.589.4

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.254 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> Could not resolve all dependencies for configuration ':_armv7DebugApkCopy'.
   > Could not find com.android.support:support-v4:26.1.0.
     Required by:
         :project:unspecified > com.apptentive:apptentive-android:4.1.2
   > Could not find com.android.support:appcompat-v7:26.1.0.
     Required by:
         :project:unspecified > com.apptentive:apptentive-android:4.1.2
   > Could not find com.android.support:cardview-v7:26.1.0.
     Required by:
         :project:unspecified > com.apptentive:apptentive-android:4.1.2
   > Could not find com.android.support:design:26.1.0.
     Required by:
         :project:unspecified > com.apptentive:apptentive-android:4.1.2
   > Could not find com.android.support:support-v4:26.1.0.
     Required by:
         :project:unspecified > org.xwalk:xwalk_core_library:23.53.589.4

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)`

Please find above the stack trace from my Phonegap build, this build is failing after you have done some changes on 13th of November.

**Comment by navadiatarun** [comment]
Please note that the Fix for this is to use the older version 4.0.2. This solved my issue.

**Comment by skykelsey** [comment]
Hello @navadiatarun. Sorry about the late response here. Did you make sure to use the latest versions of the Cordova Platform and Android plugins? If not, can you try that? I'm not sure what versions you are using, but we try to stay pretty up to date, as things do break in Cordova from time to time.

**Comment by frankus** [comment]
Closing due to inactivity.
